#!/usr/bin/env bash
# One-shot installer for the Vector LLM-driven agent swarm.
#
# Creates ~/vector-agents/{wallets,prompts,logs,state}, drops the prompts,
# generates or migrates 9 per-role wallets, creates a master faucet wallet,
# installs run.sh, renders the crontab. Idempotent — safe to re-run.
#
# Philosophy: one machine, one user, one Claude Code token, test funds.
# No permission sandbox beyond --permission-mode acceptEdits in run.sh.
# If an agent goes rogue, blast radius is its own 100 AP3X.

set -euo pipefail
umask 077

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEPLOY_DIR="$REPO_ROOT/scripts/deploy-agents"
BASE="$HOME/vector-agents"

ROLES=(
  m1-claimer m1-auditor m1-juror
  m3-staker  m3-endorser m3-challenger
  m6-proposer m6-critic  m6-endorser
)

log() { printf '[bootstrap] %s\n' "$*"; }
die() { printf '[bootstrap] ERROR: %s\n' "$*" >&2; exit 1; }

# ── Prereqs ──────────────────────────────────────────────────────────────
command -v claude  >/dev/null || die "claude CLI not found in PATH"
command -v python3 >/dev/null || die "python3 not found"
command -v git     >/dev/null || die "git not found"
python3 -c "import pycardano" 2>/dev/null \
  || die "pycardano missing. Run: cd $REPO_ROOT/Module-3/python && pip install --user --break-system-packages -e ."

# Sibling repos the agents need read access to. Cloned next to
# vector-agent-modules so run.sh's --add-dir flags resolve.
CODE_ROOT="$(dirname "$REPO_ROOT")"
for repo in agent-sdk-py vector-ai-agents; do
  if [[ ! -d "$CODE_ROOT/$repo" ]]; then
    log "Cloning $repo into $CODE_ROOT"
    git -C "$CODE_ROOT" clone "git@github.com:Apex-Fusion/$repo.git" \
      || die "Failed to clone $repo. Ensure your SSH key is in GitHub and retry."
  fi
done

# ── Layout ───────────────────────────────────────────────────────────────
log "Creating $BASE"
mkdir -p "$BASE"/{wallets,prompts,logs,state,master}
chmod 700 "$BASE/wallets" "$BASE/master"

# Install run.sh
install -m 0755 "$DEPLOY_DIR/run.sh" "$BASE/run.sh"

# Copy prompts (always refresh — they're the agent's charter)
for role in "${ROLES[@]}"; do
  src="$DEPLOY_DIR/prompts/$role.md"
  [[ -f "$src" ]] || die "Missing prompt: $src"
  install -m 0644 "$src" "$BASE/prompts/$role.md"
  mkdir -p "$BASE/state/$role"
done

# ── Master wallet ────────────────────────────────────────────────────────
if [[ ! -f "$BASE/master/wallet.skey" ]]; then
  log "Generating master wallet"
  BASE_DIR="$BASE/master" python3 - <<'PY'
import os
from pathlib import Path
from pycardano import PaymentSigningKey, PaymentVerificationKey, Address, Network
base = Path(os.environ["BASE_DIR"])
skey = PaymentSigningKey.generate()
skey.save(str(base / "wallet.skey"))
vkey = PaymentVerificationKey.from_signing_key(skey)
addr = Address(payment_part=vkey.hash(), network=Network.MAINNET)
(base / "wallet.addr").write_text(str(addr) + "\n")
print(f"  master address: {addr}")
PY
  chmod 600 "$BASE/master/wallet.skey"
else
  log "Master wallet exists: $(cat "$BASE/master/wallet.addr")"
fi

# ── Per-role wallets ─────────────────────────────────────────────────────
# Legacy migration: pull wallets from the old v1 scaffold if present so the
# funded on-chain addresses carry over (don't regenerate what we already fed
# AP3X to).
OLD_AGENT_DIR="$BASE/agents"
for role in "${ROLES[@]}"; do
  skey="$BASE/wallets/$role.skey"
  addr_file="$BASE/wallets/$role.addr"
  if [[ -f "$skey" ]]; then
    continue
  fi
  if [[ -f "$OLD_AGENT_DIR/$role/wallet.skey" ]]; then
    log "  $role: migrating wallet from old scaffold"
    install -m 0600 "$OLD_AGENT_DIR/$role/wallet.skey" "$skey"
    if [[ -f "$OLD_AGENT_DIR/$role/wallet.addr" ]]; then
      install -m 0644 "$OLD_AGENT_DIR/$role/wallet.addr" "$addr_file"
    fi
  else
    log "  $role: generating wallet"
    SKEY_PATH="$skey" ADDR_PATH="$addr_file" python3 - <<'PY'
import os
from pathlib import Path
from pycardano import PaymentSigningKey, PaymentVerificationKey, Address, Network
skey = PaymentSigningKey.generate()
skey.save(os.environ["SKEY_PATH"])
vkey = PaymentVerificationKey.from_signing_key(skey)
addr = Address(payment_part=vkey.hash(), network=Network.MAINNET)
Path(os.environ["ADDR_PATH"]).write_text(str(addr) + "\n")
print(f"  address: {addr}")
PY
    chmod 600 "$skey"
  fi
done

# ── Crontab ──────────────────────────────────────────────────────────────
# 9 roles × 2 slots per day, 80 min apart. Absolute paths so cron's
# minimal PATH doesn't matter.
USER_HOME="$HOME"
CRONFILE="$BASE/crontab.txt"
cat > "$CRONFILE" <<EOF
# Vector LLM-driven agent swarm — regenerated by bootstrap.sh
SHELL=/bin/bash
HOME=$USER_HOME
PATH=$USER_HOME/.local/bin:$USER_HOME/.npm-global/bin:/usr/local/bin:/usr/bin:/bin

# Morning slot
# m1 paused: Phase B tx builders (build_open_challenge / _commit_vote /
# _reveal_vote / _register_juror / _resolve_jury) don't exist in the repo.
# On-chain validators are live; Python client is not. Re-enable once a
# Module1Client is implemented or deploy_and_run_v10.py is recovered.
# 0  0  * * *  $BASE/run.sh m1-claimer
# 20 1  * * *  $BASE/run.sh m1-auditor
# 40 2  * * *  $BASE/run.sh m1-juror
0  4  * * *  $BASE/run.sh m3-staker
20 5  * * *  $BASE/run.sh m3-endorser
40 6  * * *  $BASE/run.sh m3-challenger
0  8  * * *  $BASE/run.sh m6-proposer
20 9  * * *  $BASE/run.sh m6-critic
40 10 * * *  $BASE/run.sh m6-endorser

# Evening slot (+12h) — m1 paused, see above
# 0  12 * * *  $BASE/run.sh m1-claimer
# 20 13 * * *  $BASE/run.sh m1-auditor
# 40 14 * * *  $BASE/run.sh m1-juror
0  16 * * *  $BASE/run.sh m3-staker
20 17 * * *  $BASE/run.sh m3-endorser
40 18 * * *  $BASE/run.sh m3-challenger
0  20 * * *  $BASE/run.sh m6-proposer
20 21 * * *  $BASE/run.sh m6-critic
40 22 * * *  $BASE/run.sh m6-endorser
EOF

log "Crontab rendered at $CRONFILE"

# ── Done ─────────────────────────────────────────────────────────────────
cat <<EOF

========================================================================
Bootstrap complete.

Layout:
  $BASE/wallets/    — 9 role wallets (one .skey per role)
  $BASE/master/     — master faucet wallet
  $BASE/prompts/    — 9 charter prompts
  $BASE/state/<role>/ — agent scratch dir (state.json, journal.md, etc.)
  $BASE/logs/       — one rolling log per role

Master address:
    $(cat "$BASE/master/wallet.addr")

NEXT:
  1. If the master wallet is fresh, send ~1000 test AP3X to it.
  2. Install the cron schedule:
         crontab $CRONFILE
  3. Smoke-test one run:
         $BASE/run.sh m3-staker
         tail -f $BASE/logs/m3-staker.log
========================================================================
EOF
